include:
  - board: nice_nano_v2
    shield: slate_sinistra
    snippet: studio-rpc-usb-uart

  - board: nice_nano_v2
    shield: slate_destra
    snippet: studio-rpc-usb-uart

  - board: nice_nano_v2
    shield: settings_reset
